name: CD
on:
 push:
   branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest # Setup an environment to run the action
    steps:
      - uses: actions/checkout@v2 # This actions copy the repository on the environment
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh 
      - uses: akhileshns/heroku-deploy@v3.12.12 # This action deploys the content on Heroku
        with:
          heroku_api_key: ${{secrets.LIVRO_LIVRE_HEROKU_API_KEY}} #The Heroku api key we stored on our repo secret
          heroku_app_name: "livro-livre-users" #The name of your heroku app - Must be unique in Heroku
          heroku_email: "livrolivreeng@gmail.com" #Your heroku yuser name
          usedocker: true